### ISSUE TITLE
There are 5370 L-functions of degree 1 and conductor in [6431, 6463] with unexpected NULL columns

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5056]
These records break the display page if we try to display one of these rows:
```
Exception on /L/1/6431 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/lfunctions/main.py", line 716, in by_url_degree_conductor_character_spectral
    return by_url_bread(degree, conductor, character, spectral_label, False)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/lfunctions/main.py", line 769, in by_url_bread
    return l_function_search(info)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_wrapper.py", line 245, in __call__
    res = self.postprocess(res, info, query)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/lfunctions/main.py", line 137, in process_search
    res = common_postprocess(res, info, query)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/lfunctions/main.py", line 132, in common_postprocess
    L['origins'] = names_and_urls(L['instance_urls'])
KeyError: 'instance_urls'
[2022-02-28 04:29:23 UTC] 500 error on URL https://beta.lmfdb.org/L/1/6431 ()

Exception on /L/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/lfunctions/main.py", line 100, in index
    return l_function_search(info)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_wrapper.py", line 245, in __call__
    res = self.postprocess(res, info, query)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/lfunctions/main.py", line 137, in process_search
    res = common_postprocess(res, info, query)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/lfunctions/main.py", line 132, in common_postprocess
    L['origins'] = names_and_urls(L['instance_urls'])
KeyError: 'instance_urls'
[2022-02-28 04:29:57 UTC] 500 error on URL https://beta.lmfdb.org/L/?hst=List&conductor=6431&degree=1&search_type=List ()
```

**Comment by AndrewVSutherland** [comment]
This seems to be fixed on beta (but still broken on production)?

**Comment by davidfarmer** [comment]
Not sure this is fixed on beta, or there is a related problem.

On beta,
when I search All L-functions of degree 1 and conductor 6431-6463,
  https://beta.lmfdb.org/L/?degree=1&conductor=6431-6463
and then I follow the link from the first one on the list
   https://beta.lmfdb.org/L/1/6431/6431.10/r0/0/0
I get a page not found:
    "Lhash 'dirichlet_L_6431.5788' not found in Lfunction table"

The next 3 on the list work fine, then the 5th one gives the same error.

**Comment by AndrewVSutherland** [comment]
Hmm, so apparently not fixed on beta, but https://www.lmfdb.org/L/?degree=1&conductor=6431-6463 throws a server error, so there is something different (which should not be the case).

**Comment by edgarcosta** [comment]
So the title of issue seems to be fixed, but beta.lmfdb.org/L/1/6431/6431.10/r0/0/0 seems to still be broken
